services: mongodb
language: node_js
node_js:
  - lts/*
install:
  - npm install
  - npm install booljs @booljs/express passport passport-http-bearer

deploy:
  provider: npm
  email: hola@pablodorado.com
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true
